/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import EDDauxiliares.StepList;
import Logica.ArbolDicotomico;
import Logica.GraphStreamArbol;
import Logica.NodoArbol;

/**
 *
 * @author ile1
 */
public class Especie_manual extends javax.swing.JFrame {
    private ArbolDicotomico arbolcargado;
    private StepList pasoscargados;
    private NodoArbol actualcargado;
    int mouseX, mouseY;
    
    public Especie_manual(ArbolDicotomico arbol, StepList pasos, NodoArbol actual) {
        initComponents();
        this.arbolcargado=arbol;
        this.pasoscargados= pasos;
        this.actualcargado= actual;
        OUTPUT.setText(actual.getEspecie());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        OUTPUT = new javax.swing.JLabel();
        arbol = new javax.swing.JLabel();
        Regresar = new javax.swing.JLabel();
        tabla_3 = new javax.swing.JLabel();
        tabla_4 = new javax.swing.JLabel();
        titulo1 = new javax.swing.JLabel();
        tabla = new javax.swing.JLabel();
        plantas1 = new javax.swing.JLabel();
        plantas2 = new javax.swing.JLabel();
        plantas3 = new javax.swing.JLabel();
        plantas4 = new javax.swing.JLabel();
        rama = new javax.swing.JLabel();
        tabla1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 500));

        bg.setBackground(new java.awt.Color(0, 102, 51));
        bg.setPreferredSize(new java.awt.Dimension(800, 500));
        bg.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bgMouseDragged(evt);
            }
        });
        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgMousePressed(evt);
            }
        });
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OUTPUT.setFont(new java.awt.Font("Vineta BT", 0, 22)); // NOI18N
        OUTPUT.setForeground(new java.awt.Color(255, 255, 255));
        OUTPUT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OUTPUT.setText("Buscando...");
        jPanel1.add(OUTPUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 140, 430, 50));

        arbol.setFont(new java.awt.Font("Vineta BT", 0, 18)); // NOI18N
        arbol.setForeground(new java.awt.Color(255, 255, 255));
        arbol.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        arbol.setText("VER ARBOL");
        arbol.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        arbol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arbolMouseClicked(evt);
            }
        });
        jPanel1.add(arbol, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 170, 60));

        Regresar.setFont(new java.awt.Font("Vineta BT", 0, 18)); // NOI18N
        Regresar.setForeground(new java.awt.Color(255, 255, 255));
        Regresar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Regresar.setText("REGRESAR");
        Regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegresarMouseClicked(evt);
            }
        });
        jPanel1.add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 170, 60));

        tabla_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo-madera-png-pisos-madera-dura_53876-627635-removebg-preview_1.png"))); // NOI18N
        jPanel1.add(tabla_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, -1, 40));

        tabla_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo-madera-png-pisos-madera-dura_53876-627635-removebg-preview_1.png"))); // NOI18N
        jPanel1.add(tabla_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, -1, 40));

        titulo1.setFont(new java.awt.Font("Vineta BT", 0, 22)); // NOI18N
        titulo1.setForeground(new java.awt.Color(0, 0, 0));
        titulo1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        titulo1.setText("Conseguiste la especie:");
        jPanel1.add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, 50));

        tabla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo-madera-png-pisos-madera-dura_53876-627635-removebg-preview.png"))); // NOI18N
        jPanel1.add(tabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 470, 190));

        plantas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pngtree-branches-and-leaves-png-image_2423895-removebg-preview_1.png"))); // NOI18N
        jPanel1.add(plantas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, -1, -1));

        plantas2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pngtree-branches-and-leaves-png-image_2423895-removebg-preview.png"))); // NOI18N
        jPanel1.add(plantas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, -1, -1));

        plantas3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pngtree-branches-and-leaves-png-image_2423895-removebg-preview_2.png"))); // NOI18N
        jPanel1.add(plantas3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, -1));

        plantas4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pngtree-branches-and-leaves-png-image_2423895-removebg-preview_3.png"))); // NOI18N
        jPanel1.add(plantas4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        rama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/39-392656_ramas-hojas-freetoedit-rama-de-hojas-png-removebg-preview.png"))); // NOI18N
        jPanel1.add(rama, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 280, -1));

        tabla1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo-madera-png-pisos-madera-dura_53876-627635-removebg-preview.png"))); // NOI18N
        jPanel1.add(tabla1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 430, 190));

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 760, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
    * Captura las coordenadas del cursor del ratón cuando se presiona el botón sobre el fondo.
    *
    * @param evt El evento del ratón que contiene la información del clic.
    */
    private void bgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_bgMousePressed

    /**
    * Maneja el evento de arrastre del ratón sobre el fondo de la ventana.
    * Permite mover la ventana arrastrando el fondo con el ratón.
    *
    * @param evt El evento de arrastre del ratón que contiene la información del evento.
    */
    private void bgMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_bgMouseDragged

    /**
    * Maneja el evento de clic del ratón en el árbol.
    *
    * Este método se invoca cuando el usuario hace clic en un nodo del árbol.
    * Crea una nueva instancia de `GraphStreamArbol` para visualizar el recorrido actual del árbol.
    * Luego, utiliza el método `mostrarRecorridoDesdeRaiz` para mostrar gráficamente el recorrido del árbol
    * desde su raíz, utilizando los pasos cargados previamente.
    *
    * @param evt El evento de clic del ratón que desencadenó esta acción.
    */
    private void arbolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arbolMouseClicked
    GraphStreamArbol grafoRecorrido = new GraphStreamArbol("Recorrido actual");
     grafoRecorrido.mostrarRecorridoDesdeRaiz(this.arbolcargado.getRaiz(), this.pasoscargados);
    }//GEN-LAST:event_arbolMouseClicked

    /**
    * Maneja el evento de clic del ratón en el botón "Regresar".
    * <p>
    * Este método crea una instancia de la clase {@code Pagina1}, pasando el árbol cargado actual como argumento.
    * Luego, hace visible la nueva página y oculta la página actual.
    * </p>
    *
    * @param evt El evento de clic del ratón que desencadenó la acción.
    */
    private void RegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMouseClicked
        Pagina1 pagina = new Pagina1(this.arbolcargado);
        pagina.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RegresarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel OUTPUT;
    private javax.swing.JLabel Regresar;
    private javax.swing.JLabel arbol;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel plantas1;
    private javax.swing.JLabel plantas2;
    private javax.swing.JLabel plantas3;
    private javax.swing.JLabel plantas4;
    private javax.swing.JLabel rama;
    private javax.swing.JLabel tabla;
    private javax.swing.JLabel tabla1;
    private javax.swing.JLabel tabla_3;
    private javax.swing.JLabel tabla_4;
    private javax.swing.JLabel titulo1;
    // End of variables declaration//GEN-END:variables
}
