/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Logica.ArbolDicotomico;
import EDDauxiliares.Step;
import EDDauxiliares.StepList;
import Logica.GraphStreamArbol;
import Logica.NodoArbol;
/**
 *
 * @author ile1
 */
public class Manual extends javax.swing.JFrame {
    
    private NodoArbol actual;  
    private StepList pasos;
    private ArbolDicotomico arbolcargado;
    int mouseX, mouseY;
    
    public Manual(ArbolDicotomico arbol) {
        initComponents();
        this.arbolcargado = arbol;
        this.actual= arbol.getRaiz();
        this.pasos= new StepList();
        Pregunta.setText(actual.getPregunta());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabla_4 = new javax.swing.JLabel();
        bg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        NO = new javax.swing.JButton();
        si = new javax.swing.JButton();
        Pregunta = new javax.swing.JLabel();
        regresar = new javax.swing.JLabel();
        tabla_3 = new javax.swing.JLabel();
        tabla1 = new javax.swing.JLabel();
        plantas1 = new javax.swing.JLabel();
        plantas2 = new javax.swing.JLabel();
        plantas3 = new javax.swing.JLabel();
        plantas4 = new javax.swing.JLabel();
        tabla2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        regresar1 = new javax.swing.JLabel();
        regresar2 = new javax.swing.JLabel();
        tabla_5 = new javax.swing.JLabel();
        MostrarArbol = new javax.swing.JButton();
        tabla_6 = new javax.swing.JLabel();

        tabla_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo-madera-png-pisos-madera-dura_53876-627635-removebg-preview_1.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 500));

        bg.setBackground(new java.awt.Color(0, 102, 51));
        bg.setPreferredSize(new java.awt.Dimension(800, 500));
        bg.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bgMouseDragged(evt);
            }
        });
        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgMousePressed(evt);
            }
        });
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NO.setBackground(new java.awt.Color(0, 102, 51));
        NO.setFont(new java.awt.Font("Vineta BT", 0, 24)); // NOI18N
        NO.setForeground(new java.awt.Color(255, 255, 255));
        NO.setText("No");
        NO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NOActionPerformed(evt);
            }
        });
        jPanel1.add(NO, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, -1, -1));

        si.setBackground(new java.awt.Color(0, 102, 51));
        si.setFont(new java.awt.Font("Vineta BT", 0, 24)); // NOI18N
        si.setForeground(new java.awt.Color(255, 255, 255));
        si.setText("Si");
        si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siActionPerformed(evt);
            }
        });
        jPanel1.add(si, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        Pregunta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Pregunta.setForeground(new java.awt.Color(255, 255, 255));
        Pregunta.setText("Esperando...");
        Pregunta.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                PreguntaPropertyChange(evt);
            }
        });
        jPanel1.add(Pregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 310, 40));

        regresar.setFont(new java.awt.Font("Vineta BT", 0, 18)); // NOI18N
        regresar.setForeground(new java.awt.Color(255, 255, 255));
        regresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regresar.setText("<<REGRESAR");
        regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regresarMouseClicked(evt);
            }
        });
        jPanel1.add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 200, 60));

        tabla_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo-madera-png-pisos-madera-dura_53876-627635-removebg-preview_1.png"))); // NOI18N
        jPanel1.add(tabla_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        tabla1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo-madera-png-pisos-madera-dura_53876-627635-removebg-preview.png"))); // NOI18N
        jPanel1.add(tabla1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 90, 300, 200));

        plantas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pngtree-branches-and-leaves-png-image_2423895-removebg-preview_1.png"))); // NOI18N
        jPanel1.add(plantas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, -1, -1));

        plantas2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pngtree-branches-and-leaves-png-image_2423895-removebg-preview.png"))); // NOI18N
        jPanel1.add(plantas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, -1, -1));

        plantas3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pngtree-branches-and-leaves-png-image_2423895-removebg-preview_2.png"))); // NOI18N
        jPanel1.add(plantas3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, -1));

        plantas4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pngtree-branches-and-leaves-png-image_2423895-removebg-preview_3.png"))); // NOI18N
        jPanel1.add(plantas4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        tabla2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo-madera-png-pisos-madera-dura_53876-627635-removebg-preview.png"))); // NOI18N
        jPanel1.add(tabla2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 300, 200));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pngtree-a-big-tree-with-green-leaf-on-transparent-background-genrative-ai-png-image_11931910.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 150, 190));

        regresar1.setFont(new java.awt.Font("Vineta BT", 0, 18)); // NOI18N
        regresar1.setForeground(new java.awt.Color(255, 255, 255));
        regresar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regresar1.setText("<<REGRESAR");
        regresar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regresar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regresar1MouseClicked(evt);
            }
        });
        jPanel1.add(regresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 60));

        regresar2.setFont(new java.awt.Font("Vineta BT", 0, 18)); // NOI18N
        regresar2.setForeground(new java.awt.Color(255, 255, 255));
        regresar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regresar2.setText("<<REGRESAR");
        regresar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regresar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regresar2MouseClicked(evt);
            }
        });
        jPanel1.add(regresar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 200, 60));

        tabla_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo-madera-png-pisos-madera-dura_53876-627635-removebg-preview_1.png"))); // NOI18N
        jPanel1.add(tabla_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        MostrarArbol.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MostrarArbol.setForeground(new java.awt.Color(255, 255, 255));
        MostrarArbol.setText("Mostrar Recorrido");
        MostrarArbol.setContentAreaFilled(false);
        MostrarArbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarArbolActionPerformed(evt);
            }
        });
        jPanel1.add(MostrarArbol, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 233, 230, 40));

        tabla_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo-madera-png-pisos-madera-dura_53876-627635-removebg-preview_1.png"))); // NOI18N
        jPanel1.add(tabla_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, -1, -1));

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 760, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_bgMousePressed

    private void bgMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_bgMouseDragged

    private void regresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresarMouseClicked
        Pagina1 pagina = new Pagina1(this.arbolcargado);
        pagina.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_regresarMouseClicked

    private void siActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siActionPerformed
      if (actual != null) {
        if (actual.getEspecie() == null) {
            pasos.add(new Step(actual.getPregunta(), true));
            actual = actual.getRespuestaSi();

            if (actual.getEspecie() == null) {
                Pregunta.setText(actual.getPregunta());
            } else {
                // Ya llegaste a una hoja → ir a siguiente interfaz
                Especie_manual especie = new Especie_manual(this.arbolcargado,this.pasos, this.actual);
                this.setVisible(false);
                especie.setVisible(true);
            }
        } else {
            // Ya era hoja desde el principio (caso raro pero lo manejamos igual)
            Especie_manual especie = new Especie_manual(this.arbolcargado,this.pasos, this.actual);
            this.setVisible(false);
            especie.setVisible(true);
        }
    }
    }//GEN-LAST:event_siActionPerformed

    private void PreguntaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_PreguntaPropertyChange
        
    }//GEN-LAST:event_PreguntaPropertyChange

    private void NOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NOActionPerformed
       if (actual != null) {
        if (actual.getEspecie() == null) {
            pasos.add(new Step(actual.getPregunta(), false));
            actual = actual.getRespuestaNo();

            if (actual.getEspecie() == null) {
                Pregunta.setText(actual.getPregunta());
            } else {
                // Ya llegaste a una hoja → ir a siguiente interfaz
                Especie_manual especie = new Especie_manual(this.arbolcargado,this.pasos, this.actual);
                this.setVisible(false);
                especie.setVisible(true);
            }
        } else {
            // Ya era hoja desde el principio (caso raro pero lo manejamos igual)
            Especie_manual especie = new Especie_manual(this.arbolcargado,this.pasos, this.actual);
            this.setVisible(false);
            especie.setVisible(true);
        }
    }
    }//GEN-LAST:event_NOActionPerformed

    private void regresar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_regresar1MouseClicked

    private void regresar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresar2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_regresar2MouseClicked

    private void MostrarArbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarArbolActionPerformed
     GraphStreamArbol grafoRecorrido = new GraphStreamArbol("Recorrido actual");
     grafoRecorrido.mostrarRecorridoDesdeRaiz(this.arbolcargado.getRaiz(), this.pasos);
    }//GEN-LAST:event_MostrarArbolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MostrarArbol;
    public javax.swing.JButton NO;
    public javax.swing.JLabel Pregunta;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel plantas1;
    private javax.swing.JLabel plantas2;
    private javax.swing.JLabel plantas3;
    private javax.swing.JLabel plantas4;
    private javax.swing.JLabel regresar;
    private javax.swing.JLabel regresar1;
    private javax.swing.JLabel regresar2;
    public javax.swing.JButton si;
    private javax.swing.JLabel tabla1;
    private javax.swing.JLabel tabla2;
    private javax.swing.JLabel tabla_3;
    private javax.swing.JLabel tabla_4;
    private javax.swing.JLabel tabla_5;
    private javax.swing.JLabel tabla_6;
    // End of variables declaration//GEN-END:variables
}
